stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  tags:
    - batata
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE/gateway:latest /home/ubuntu/gitlab_devops_exams/gateway/
    - docker push $CI_REGISTRY_IMAGE/gateway:latest
    - docker build -t $CI_REGISTRY_IMAGE/orders:latest /home/ubuntu/gitlab_devops_exams/orders/
    - docker push $CI_REGISTRY_IMAGE/orders:latest
    - docker build -t $CI_REGISTRY_IMAGE/users:latest /home/ubuntu/gitlab_devops_exams/users/
    - docker push $CI_REGISTRY_IMAGE/users:latest

# Deploy Gateway
deploy_gateway_dev:
  stage: deploy
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install gateway ~/gitlab_devops_exams/gateway/gateway --set image.repository=$CI_REGISTRY_IMAGE/gateway --namespace dev

deploy_gateway_qa:
  stage: deploy
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install gateway ~/gitlab_devops_exams/gateway/gateway --set image.repository=$CI_REGISTRY_IMAGE/gateway --namespace qa

deploy_gateway_staging:
  stage: deploy
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install gateway ~/gitlab_devops_exams/gateway/gateway --set image.repository=$CI_REGISTRY_IMAGE/gateway --namespace staging

deploy_gateway_prod:
  stage: deploy
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install gateway ~/gitlab_devops_exams/gateway/gateway --set image.repository=$CI_REGISTRY_IMAGE/gateway --namespace prod
  when: manual

# Deploy Orders
deploy_orders_dev:
  stage: deploy
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install orders ~/gitlab_devops_exams/orders/orders --set image.repository=$CI_REGISTRY_IMAGE/orders --namespace dev

deploy_orders_qa:
  stage: deploy
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install orders ~/gitlab_devops_exams/orders/orders --set image.repository=$CI_REGISTRY_IMAGE/orders --namespace qa

deploy_orders_staging:
  stage: deploy
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install orders ~/gitlab_devops_exams/orders/orders --set image.repository=$CI_REGISTRY_IMAGE/orders --namespace staging

deploy_orders_prod:
  stage: deploy
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install orders ~/gitlab_devops_exams/orders/orders --set image.repository=$CI_REGISTRY_IMAGE/orders --namespace prod
  when: manual

# Deploy Users
deploy_users_dev:
  stage: deploy
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install users ~/gitlab_devops_exams/users/users --set image.repository=$CI_REGISTRY_IMAGE/users --namespace dev

deploy_users_qa:
  stage: deploy
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install users ~/gitlab_devops_exams/users/users --set image.repository=$CI_REGISTRY_IMAGE/users --namespace qa

deploy_users_staging:
  stage: deploy
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install users ~/gitlab_devops_exams/users/users --set image.repository=$CI_REGISTRY_IMAGE/users --namespace staging

deploy_users_prod:
  stage: deploy
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - helm upgrade --install users ~/gitlab_devops_exams/users/users --set image.repository=$CI_REGISTRY_IMAGE/users --namespace prod
  when: manual
