stages:
  - build_and_push
  - deploy_dev
  - deploy_qa
  - deploy_staging
  - deploy_prod

build_and_push:
  stage: build_and_push
  tags:
    - batata
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE/gateway:latest /home/ubuntu/gitlab_devops_exams/gateway/
    - docker push $CI_REGISTRY_IMAGE/gateway:latest
    - docker build -t $CI_REGISTRY_IMAGE/orders:latest /home/ubuntu/gitlab_devops_exams/orders/
    - docker push $CI_REGISTRY_IMAGE/orders:latest
    - docker build -t $CI_REGISTRY_IMAGE/users:latest /home/ubuntu/gitlab_devops_exams/users/
    - docker push $CI_REGISTRY_IMAGE/users:latest

# Deploy dev
deploy_dev:
  stage: deploy_dev
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - cat .kube/config
    -  helm upgrade --install gateway gateway/gateway/ --set image.repository=$CI_REGISTRY_IMAGE/gateway --namespace dev  --kubeconfig=.kube/config
    -  helm upgrade --install users users/users/ --set image.repository=$CI_REGISTRY_IMAGE/users --namespace dev  --kubeconfig=.kube/config
    -  helm upgrade --install orders orders/orders/ --set image.repository=$CI_REGISTRY_IMAGE/orders --namespace dev  --kubeconfig=.kube/config




# Deploy qa
deploy_qa:
  stage: deploy_qa
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - cat .kube/config
    -  helm upgrade --install gateway gateway/gateway/ --set image.repository=$CI_REGISTRY_IMAGE/gateway --namespace qa  --kubeconfig=.kube/config
    -  helm upgrade --install users users/users/ --set image.repository=$CI_REGISTRY_IMAGE/users --namespace qa  --kubeconfig=.kube/config
    -  helm upgrade --install orders orders/orders/ --set image.repository=$CI_REGISTRY_IMAGE/orders --namespace qa  --kubeconfig=.kube/config



# Deploy staging
deploy_staging:
  stage: deploy_staging
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - cat .kube/config
    -  helm upgrade --install gateway gateway/gateway/ --set image.repository=$CI_REGISTRY_IMAGE/gateway --namespace staging  --kubeconfig=.kube/config
    -  helm upgrade --install users users/users/ --set image.repository=$CI_REGISTRY_IMAGE/users --namespace staging  --kubeconfig=.kube/config
    -  helm upgrade --install orders orders/orders/ --set image.repository=$CI_REGISTRY_IMAGE/orders --namespace staging  --kubeconfig=.kube/config



# Deploy prod
deploy_prod:
  stage: deploy_prod
  tags:
    - batata
  only:
    - main
  when: manual
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - cat .kube/config
    - helm upgrade --install gateway gateway/gateway/ --set image.repository=$CI_REGISTRY_IMAGE/gateway --namespace prod --kubeconfig=.kube/config
    - helm upgrade --install users users/users/ --set image.repository=$CI_REGISTRY_IMAGE/users --namespace prod --kubeconfig=.kube/config
    - helm upgrade --install orders orders/orders/ --set image.repository=$CI_REGISTRY_IMAGE/orders --namespace prod --kubeconfig=.kube/config












