stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  tags:
    - batata
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE/gateway:latest /home/ubuntu/gitlab_devops_exams/gateway/
    - docker push $CI_REGISTRY_IMAGE/gateway:latest
    - docker build -t $CI_REGISTRY_IMAGE/orders:latest /home/ubuntu/gitlab_devops_exams/orders/
    - docker push $CI_REGISTRY_IMAGE/orders:latest
    - docker build -t $CI_REGISTRY_IMAGE/users:latest /home/ubuntu/gitlab_devops_exams/users/
    - docker push $CI_REGISTRY_IMAGE/users:latest

# Deploy Gateway
deploy_gateway_dev:
  stage: deploy
  tags:
    - batata
  script:
    - rm -Rf .kube
    - mkdir .kube
    - ls
    - cat $KUBE_CONFIG > .kube/config
    - cat .kube/config
    -  helm upgrade --install gateway /gitlab_devops_exams/gateway/gateway --set image.repository=$CI_REGISTRY_IMAGE/gateway --namespace dev  --kubeconfig=.kube/config

