stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  tags:
    - batata
  script:
    - docker build -t $CI_REGISTRY_IMAGE/gateway:latest /home/ubuntu/gitlab_devops_exams/gateway/
    - docker push $CI_REGISTRY_IMAGE/gateway:latest
    - docker build -t $CI_REGISTRY_IMAGE/orders:latest /home/ubuntu/gitlab_devops_exams/orders/
    - docker push $CI_REGISTRY_IMAGE/orders:latest
    - docker build -t $CI_REGISTRY_IMAGE/users:latest /home/ubuntu/gitlab_devops_exams/users/
    - docker push $CI_REGISTRY_IMAGE/users:latest

