image: docker:latest

services:
  - docker:dind

stages:
  - build_and_push
  - deploy

before_script:
  - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"

build_and_push:
  stage: build_and_push
  script:
    - docker build -t azzouz953/gateway:latest gateway/
    - docker push azzouz953/gateway:latest
    - docker build -t azzouz953/orders:latest orders/
    - docker push azzouz953/orders:latest
    - docker build -t azzouz953/users:latest users/
    - docker push azzouz953/users:latest

.deploy_template: &deploy
  stage: deploy
  script:
    - helm upgrade --install $SERVICE $CHART_PATH --set image.repository=azzouz953/$SERVICE --namespace $KUBE_NAMESPACE

.deploy_to_all_environments: &deploy_all
  dev:
    <<: *deploy
    variables:
      KUBE_NAMESPACE: dev
    only:
      - develop
  qa:
    <<: *deploy
    variables:
      KUBE_NAMESPACE: qa
    only:
      - qa
  staging:
    <<: *deploy
    variables:
      KUBE_NAMESPACE: staging
    only:
      - staging
  prod:
    <<: *deploy
    variables:
      KUBE_NAMESPACE: prod
    only:
      - main
    when: manual

deploy_gateway: 
  <<: *deploy_all
  variables:
    SERVICE: gateway
    CHART_PATH: ~/gitlab_devops_exams/gateway/gateway

deploy_orders:
  <<: *deploy_all
  variables:
    SERVICE: orders
    CHART_PATH: ~/gitlab_devops_exams/orders/orders

deploy_users:
  <<: *deploy_all
  variables:
    SERVICE: users
    CHART_PATH: ~/gitlab_devops_exams/users/users
