stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  tags:
    - batata
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE/gateway:latest /home/ubuntu/gitlab_devops_exams/gateway/
    - docker push $CI_REGISTRY_IMAGE/gateway:latest
    - docker build -t $CI_REGISTRY_IMAGE/orders:latest /home/ubuntu/gitlab_devops_exams/orders/
    - docker push $CI_REGISTRY_IMAGE/orders:latest
    - docker build -t $CI_REGISTRY_IMAGE/users:latest /home/ubuntu/gitlab_devops_exams/users/
    - docker push $CI_REGISTRY_IMAGE/users:latest

# Deploy Gateway
deploy_gateway_dev:
  stage: deploy
  script:
    - helm upgrade --install gateway ~/gitlab_devops_exams/gateway/gateway --set image.repository=$CI_REGISTRY_IMAGE/gateway --namespace dev
  only:
    - develop

deploy_gateway_qa:
  stage: deploy
  script:
    - helm upgrade --install gateway ~/gitlab_devops_exams/gateway/gateway --set image.repository=$CI_REGISTRY_IMAGE/gateway --namespace qa
  only:
    - qa

deploy_gateway_staging:
  stage: deploy
  script:
    - helm upgrade --install gateway ~/gitlab_devops_exams/gateway/gateway --set image.repository=$CI_REGISTRY_IMAGE/gateway --namespace staging
  only:
    - staging

deploy_gateway_prod:
  stage: deploy
  script:
    - helm upgrade --install gateway ~/gitlab_devops_exams/gateway/gateway --set image.repository=$CI_REGISTRY_IMAGE/gateway --namespace prod
  only:
    - main
  when: manual

# Deploy Orders
deploy_orders_dev:
  stage: deploy
  script:
    - helm upgrade --install orders ~/gitlab_devops_exams/orders/orders --set image.repository=$CI_REGISTRY_IMAGE/orders --namespace dev
  only:
    - develop

deploy_orders_qa:
  stage: deploy
  script:
    - helm upgrade --install orders ~/gitlab_devops_exams/orders/orders --set image.repository=$CI_REGISTRY_IMAGE/orders --namespace qa
  only:
    - qa

deploy_orders_staging:
  stage: deploy
  script:
    - helm upgrade --install orders ~/gitlab_devops_exams/orders/orders --set image.repository=$CI_REGISTRY_IMAGE/orders --namespace staging
  only:
    - staging

deploy_orders_prod:
  stage: deploy
  script:
    - helm upgrade --install orders ~/gitlab_devops_exams/orders/orders --set image.repository=$CI_REGISTRY_IMAGE/orders --namespace prod
  only:
    - main
  when: manual

# Deploy Users
deploy_users_dev:
  stage: deploy
  script:
    - helm upgrade --install users ~/gitlab_devops_exams/users/users --set image.repository=$CI_REGISTRY_IMAGE/users --namespace dev
  only:
    - develop

deploy_users_qa:
  stage: deploy
  script:
    - helm upgrade --install users ~/gitlab_devops_exams/users/users --set image.repository=$CI_REGISTRY_IMAGE/users --namespace qa
  only:
    - qa

deploy_users_staging:
  stage: deploy
  script:
    - helm upgrade --install users ~/gitlab_devops_exams/users/users --set image.repository=$CI_REGISTRY_IMAGE/users --namespace staging
  only:
    - staging

deploy_users_prod:
  stage: deploy
  script:
    - helm upgrade --install users ~/gitlab_devops_exams/users/users --set image.repository=$CI_REGISTRY_IMAGE/users --namespace prod
  only:
    - main
  when: manual
