stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  tags:
    - batata
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE/gateway:latest /home/ubuntu/gitlab_devops_exams/gateway/
    - docker push $CI_REGISTRY_IMAGE/gateway:latest
    - docker build -t $CI_REGISTRY_IMAGE/orders:latest /home/ubuntu/gitlab_devops_exams/orders/
    - docker push $CI_REGISTRY_IMAGE/orders:latest
    - docker build -t $CI_REGISTRY_IMAGE/users:latest /home/ubuntu/gitlab_devops_exams/users/
    - docker push $CI_REGISTRY_IMAGE/users:latest

.deploy_template: &deploy
  stage: deploy
  script:
    - helm upgrade --install $SERVICE $CHART_PATH --set image.repository=$CI_REGISTRY_IMAGE --namespace $KUBE_NAMESPACE

.deploy_to_all_environments: &deploy_all
  dev:
    <<: *deploy
    variables:
      KUBE_NAMESPACE: dev
    only:
      - develop
  qa:
    <<: *deploy
    variables:
      KUBE_NAMESPACE: qa
    only:
      - qa
  staging:
    <<: *deploy
    variables:
      KUBE_NAMESPACE: staging
    only:
      - staging
  prod:
    <<: *deploy
    variables:
      KUBE_NAMESPACE: prod
    only:
      - main
    when: manual

deploy_gateway: 
  <<: *deploy_all
  variables:
    SERVICE: gateway
    CHART_PATH: ~/gitlab_devops_exams/gateway/gateway

deploy_orders:
  <<: *deploy_all
  variables:
    SERVICE: orders
    CHART_PATH: ~/gitlab_devops_exams/orders/orders

deploy_users:
  <<: *deploy_all
  variables:
    SERVICE: users
    CHART_PATH: ~/gitlab_devops_exams/users/users
