apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  USERS_SERVICE_URL: "{{ .Values.configMap.data.USERS_SERVICE_URL }}"
  ORDERS_SERVICE_URL: "{{ .Values.configMap.data.USERS_SERVICE_URL }}"
